% n=-20:1:20;
x=0:20;
% f_o= 32;
% f_s= 64 ;
% p = cos(2*pi*f_o*n/f_s); 
% q= cos(2*pi*f_o*x/f_s);
q= sin(x);
ft = fft(q,20);
figure;
stem(abs(ft));
title('FFT of q');
xlabel('Frequency (Hz)');
ylabel('Magnitude');
grid on;
% stem(n,p,'b');
% hold on;
% plot(x,q);
% hold off;
% % plot(x,q);
% title('Signal p[n] = cos(2*pi*f_o*n/f_s)');
% xlabel('n');
% ylabel('p[n]');
% grid on;
